from __future__ import annotations

from urllib.parse import quote


def amazon_affiliate_url(asin: str, partner_tag: str, *, marketplace: str = "www.amazon.com.br") -> str:
    """Monta o link de associado da Amazon no mesmo formato do SiteStripe.

    Preferir esta funcao a um template com ``{url}``: montar o link canonico a
    partir do ASIN garante que a tag sempre entre, sem depender de o link
    original ja ter (ou nao) query string.
    """
    tag = partner_tag.strip()
    if not asin.strip() or not tag:
        raise ValueError("asin e partner_tag sao obrigatorios para o link de afiliado Amazon")
    return f"https://{marketplace}/dp/{asin.strip()}?tag={tag}&linkCode=ll1&language=pt_BR&ref_=as_li_ss_tl"


def apply_affiliate_template(
    template: str | None,
    url: str,
    *,
    affiliate_id: str = "",
    source: str = "",
    external_id: str = "",
) -> str:
    """Apply a user-provided official affiliate link template.

    The system does not invent affiliate parameters for marketplaces. Configure
    templates generated by the official affiliate program, for example:
    https://example.com/redirect?url={encoded_url}&aff={affiliate_id}
    """

    if not template:
        return url

    values = {
        "url": url,
        "encoded_url": quote(url, safe=""),
        "affiliate_id": affiliate_id,
        "source": source,
        "external_id": external_id,
    }
    try:
        return template.format(**values)
    except KeyError:
        return url
