from __future__ import annotations

from urllib.parse import quote


def apply_affiliate_template(
    template: str | None,
    url: str,
    *,
    affiliate_id: str = "",
    source: str = "",
    external_id: str = "",
) -> str:
    """Apply a user-provided official affiliate link template.

    The system does not invent affiliate parameters for marketplaces. Configure
    templates generated by the official affiliate program, for example:
    https://example.com/redirect?url={encoded_url}&aff={affiliate_id}
    """

    if not template:
        return url

    values = {
        "url": url,
        "encoded_url": quote(url, safe=""),
        "affiliate_id": affiliate_id,
        "source": source,
        "external_id": external_id,
    }
    try:
        return template.format(**values)
    except KeyError:
        return url
